### ISSUE TITLE
jsonvalidate fxn, error message clarification

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/geojsonlint#7]
@ateucher not sure how to interpret this message:

```r
geojson_validate('{ "type": "FeatureCollection" }', error = TRUE)
#> Error: 1 error validating json:
#> 	- data: no (or more than one) schemas match
```

what does `no (or more than one) schemas match` mean? 

with another fxn I get 

```r
geojson_hint('{ "type": "FeatureCollection" }', error = TRUE)
#> Error: Line 1
#>     - "features" property required
```

**Comment by ateucher** [comment]
It looks like it's generic message from `is-my-json-valid` when one of the required fields in the schema isn't there. See https://github.com/mafintosh/is-my-json-valid/issues/82 and https://github.com/mafintosh/is-my-json-valid/issues/38. Apparently it's when a field defined in the schema by `oneOf` or `anyOf` doesn't fit or isn't present (such as the [geometry type](https://github.com/ropenscilabs/geojsonlint/blob/master/inst/schema/geojson.json#L118)??). Unfortunately if `is-my-json-valid` isn't going to be more specific, I don't think we can be either.

**Comment by sckott** [comment]
okay, but we know it is helpful for some errors at least. And I imagine we can get an improved schema at some point?  

I'll add to docs that some errors won't have specific messages. But this option fast, so there's a tradeoff there

**Comment by ateucher** [comment]
Yup, it is helpful for some errors... and it is fast. I'm not sure if the problem is with the schema, or with the reporting from `is-my-json-valid` - judging from the comments in those issues, it could be done better. But I'll keep my eyes out for a better schema, or ways to improve the current one...

**Comment by sckott** [comment]
> I'm not sure if the problem is with the schema, or with the reporting from is-my-json-valid

Ah right! Well either way, it may improve
